# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT my_web_apps.wsgi

beta_settings:
    cloud_sql_instances: maneeshd-apps:asia-south1:maneeshd-datastore

runtime_config:
  python_version: 3
# [END runtime]
